source 'https://rubygems.org'
source 'https://rubygems.org'

gem "rails", ">= 3.2.17"

gem 'sqlite3'
group :assets do
  gem 'sass-rails',   '3.2.3'
  gem 'coffee-rails', '3.2.1'
  gem 'uglifier', '1.0.3'
end

gem "jquery-rails", ">= 3.1.3"

gem "brakeman", :group => [:development]
gem "rspec-rails", "2.12.2", :group => [:development, :test]
gem "factory_girl_rails", "4.1.0", :group => [:development, :test]
gem "email_spec", "1.2.1", :group => :test
gem "cucumber-rails", "1.3.0", :group => :test, :require => false

gem "capybara", "2.0.1", :group => :test
gem "database_cleaner", "0.7.2", :group => :test
gem "launchy", "2.1.0", :group => :test
gem "devise", ">= 4.7.1"
gem "therubyracer", "0.11.3", :group => :assets, :platform => :ruby
# gem 'libv8', '3.11.8.13'
gem "pry"
gem "pry-doc"

